name: CI
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
  issue_comment:
    branches:
      - *
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm ci
    - name: Install the browsers
      run: npx playwright install
    - name: Install the operating-system dependencies
      run: npx playwright install-deps
    - name: Run end-to-end tests
      run: npm run coverage
    - run: npx nyc report --reporter=lcovonly
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
